import {
  Database, Server, Shield, Activity, Users, Settings, Code, Link, FileText,
  Box, Cloud, Cpu, Globe, HardDrive, Key, Lock, Network, Smartphone,
  Terminal, Wifi, Zap, AlertTriangle, CheckCircle, Info, XCircle,
  Briefcase, Building, Folder, Home, Inbox, Map, Paperclip,
  Book, Bookmark, Edit, Image, User, Component, Layout, List, File,
  ShieldAlert, ShieldCheck, Unlock, Eye, EyeOff, Search, Filter,
  ArrowRight, ArrowLeft, ArrowUp, ArrowDown, RefreshCw, GitBranch,
  GitCommit, GitMerge, GitPullRequest, Hexagon, Triangle, Circle, Square,
  AlignLeft, AlignCenter, AlignRight, AlignJustify, Bold, Italic, Underline,
  Strikethrough, Type, Hash, DollarSign, Percent, AtSign, Phone, Mail,
  MessageSquare, MessageCircle, Send, Bell, Calendar, Clock, Watch,
  Timer, Play, Pause, SquarePlay, SkipBack, SkipForward, Volume2,
  VolumeX, Mic, Video, Camera, Monitor, Laptop, Tablet, Printer,
  Mouse, Keyboard, Headphones, Speaker, Tv, Radio, Battery, BatteryCharging,
  Plug, Power, ZapOff, Sun, Moon, CloudRain, CloudSnow, CloudLightning,
  Wind, Droplet, Flame, Thermometer, Compass, Navigation, MapPin,
  Crosshair, Target, Flag, BookmarkMinus, BookmarkPlus, Star, Heart,
  ThumbsUp, ThumbsDown, Smile, Frown, Meh, ShoppingCart, ShoppingBag,
  CreditCard, Wallet, Tag, Ticket, Gift, Package, Truck, Plane, Car,
  Bike, Train, Ship, Anchor, LifeBuoy, Wrench, Hammer,
  Scissors, PenTool, Brush, Palette, Pipette, Ruler, TestTube, FlaskConical,
  Microscope, Stethoscope, Syringe, Pill, ActivitySquare, HeartPulse,
  Brain, Dna, Atom, Rocket, Satellite, Telescope, Radar, ShieldHalf,
  ShieldOff, KeyRound, LockKeyhole, LockOpen, Fingerprint, ScanFace,
  ScanLine, QrCode, Barcode, Scan, Maximize, Minimize, Plus, Minus,
  X, Check, ChevronUp, ChevronDown, ChevronLeft, ChevronRight,
  ChevronsUp, ChevronsDown, ChevronsLeft, ChevronsRight, ArrowUpRight,
  ArrowUpLeft, ArrowDownRight, ArrowDownLeft, Move, MoveHorizontal,
  MoveVertical, MoveDiagonal, MoveDiagonal2, Maximize2, Minimize2,
  ZoomIn, ZoomOut, RotateCcw, RotateCw, Repeat, Repeat1, Shuffle,
  Share, Share2, Download, Upload, DownloadCloud, UploadCloud,
  CloudOff, CloudDrizzle, CloudFog, CloudHail, CloudMoon, CloudSun,
  SunDim, SunMedium, MoonStar, Stars, Sparkles, Wand2,
  Sword, ShieldBan, ShieldEllipsis, ShieldQuestion, ShieldX,
  UserCheck, UserMinus, UserPlus, UserX, Users2, UserCog,
  Building2, Store, Factory, Warehouse, School, GraduationCap,
  Library, Landmark, Church, Tent, Castle, Crown, Gem, Trophy,
  Medal, Award, Badge, BadgeCheck, BadgeAlert, BadgeX, BadgeInfo,
  BadgeHelp, BadgeMinus, BadgePlus, BadgePercent,
  FileArchive, FileAudio, FileBadge, FileBadge2, FileBarChart,
  FileBarChart2, FileBox, FileCheck, FileCheck2, FileClock, FileCode,
  FileCode2, FileCog, FileDiff, FileDigit, FileDown, FileEdit,
  FileHeart, FileImage, FileInput, FileJson, FileJson2, FileKey,
  FileKey2, FileLineChart, FileLock, FileLock2, FileMinus, FileMinus2,
  FileMusic, FileOutput, FilePen, FilePenLine, FilePieChart,
  FilePlus, FilePlus2, FileQuestion, FileSearch, FileSearch2,
  FileSignature, FileSpreadsheet, FileStack, FileSymlink, FileTerminal,
  FileText as FileText2, FileType, FileType2, FileUp, FileVideo,
  FileVolume, FileVolume2, FileWarning, FileX, FileX2, Files,
  FolderArchive, FolderCheck, FolderClock, FolderClosed, FolderCog,
  FolderDot, FolderDown, FolderEdit, FolderGit, FolderGit2, FolderHeart,
  FolderInput, FolderKey, FolderLock, FolderMinus, FolderOpen,
  FolderOpenDot, FolderOutput, FolderPen, FolderPlus, FolderRoot,
  FolderSearch, FolderSearch2, FolderSymlink, FolderSync, FolderTree,
  FolderUp, FolderX, Folders
} from 'lucide-react';

export const icons = {
  Database, Server, Shield, Activity, Users, Settings, Code, Link, FileText,
  Box, Cloud, Cpu, Globe, HardDrive, Key, Lock, Network, Smartphone,
  Terminal, Wifi, Zap, AlertTriangle, CheckCircle, Info, XCircle,
  Briefcase, Building, Folder, Home, Inbox, Map, Paperclip,
  Book, Bookmark, Edit, Image, User, Component, Layout, List, File,
  ShieldAlert, ShieldCheck, Unlock, Eye, EyeOff, Search, Filter,
  ArrowRight, ArrowLeft, ArrowUp, ArrowDown, RefreshCw, GitBranch,
  GitCommit, GitMerge, GitPullRequest, Hexagon, Triangle, Circle, Square,
  AlignLeft, AlignCenter, AlignRight, AlignJustify, Bold, Italic, Underline,
  Strikethrough, Type, Hash, DollarSign, Percent, AtSign, Phone, Mail,
  MessageSquare, MessageCircle, Send, Bell, Calendar, Clock, Watch,
  Timer, Play, Pause, SquarePlay, SkipBack, SkipForward, Volume2,
  VolumeX, Mic, Video, Camera, Monitor, Laptop, Tablet, Printer,
  Mouse, Keyboard, Headphones, Speaker, Tv, Radio, Battery, BatteryCharging,
  Plug, Power, ZapOff, Sun, Moon, CloudRain, CloudSnow, CloudLightning,
  Wind, Droplet, Flame, Thermometer, Compass, Navigation, MapPin,
  Crosshair, Target, Flag, BookmarkMinus, BookmarkPlus, Star, Heart,
  ThumbsUp, ThumbsDown, Smile, Frown, Meh, ShoppingCart, ShoppingBag,
  CreditCard, Wallet, Tag, Ticket, Gift, Package, Truck, Plane, Car,
  Bike, Train, Ship, Anchor, LifeBuoy, Wrench, Hammer,
  Scissors, PenTool, Brush, Palette, Pipette, Ruler, TestTube, FlaskConical,
  Microscope, Stethoscope, Syringe, Pill, ActivitySquare, HeartPulse,
  Brain, Dna, Atom, Rocket, Satellite, Telescope, Radar, ShieldHalf,
  ShieldOff, KeyRound, LockKeyhole, LockOpen, Fingerprint, ScanFace,
  ScanLine, QrCode, Barcode, Scan, Maximize, Minimize, Plus, Minus,
  X, Check, ChevronUp, ChevronDown, ChevronLeft, ChevronRight,
  ChevronsUp, ChevronsDown, ChevronsLeft, ChevronsRight, ArrowUpRight,
  ArrowUpLeft, ArrowDownRight, ArrowDownLeft, Move, MoveHorizontal,
  MoveVertical, MoveDiagonal, MoveDiagonal2, Maximize2, Minimize2,
  ZoomIn, ZoomOut, RotateCcw, RotateCw, Repeat, Repeat1, Shuffle,
  Share, Share2, Download, Upload, DownloadCloud, UploadCloud,
  CloudOff, CloudDrizzle, CloudFog, CloudHail, CloudMoon, CloudSun,
  SunDim, SunMedium, MoonStar, Stars, Sparkles, Wand2,
  Sword, ShieldBan, ShieldEllipsis, ShieldQuestion, ShieldX,
  UserCheck, UserMinus, UserPlus, UserX, Users2, UserCog,
  Building2, Store, Factory, Warehouse, School, GraduationCap,
  Library, Landmark, Church, Tent, Castle, Crown, Gem, Trophy,
  Medal, Award, Badge, BadgeCheck, BadgeAlert, BadgeX, BadgeInfo,
  BadgeHelp, BadgeMinus, BadgePlus, BadgePercent,
  FileArchive, FileAudio, FileBadge, FileBadge2, FileBarChart,
  FileBarChart2, FileBox, FileCheck, FileCheck2, FileClock, FileCode,
  FileCode2, FileCog, FileDiff, FileDigit, FileDown, FileEdit,
  FileHeart, FileImage, FileInput, FileJson, FileJson2, FileKey,
  FileKey2, FileLineChart, FileLock, FileLock2, FileMinus, FileMinus2,
  FileMusic, FileOutput, FilePen, FilePenLine, FilePieChart,
  FilePlus, FilePlus2, FileQuestion, FileSearch, FileSearch2,
  FileSignature, FileSpreadsheet, FileStack, FileSymlink, FileTerminal,
  FileText2, FileType, FileType2, FileUp, FileVideo,
  FileVolume, FileVolume2, FileWarning, FileX, FileX2, Files,
  FolderArchive, FolderCheck, FolderClock, FolderClosed, FolderCog,
  FolderDot, FolderDown, FolderEdit, FolderGit, FolderGit2, FolderHeart,
  FolderInput, FolderKey, FolderLock, FolderMinus, FolderOpen,
  FolderOpenDot, FolderOutput, FolderPen, FolderPlus, FolderRoot,
  FolderSearch, FolderSearch2, FolderSymlink, FolderSync, FolderTree,
  FolderUp, FolderX, Folders
};

export type IconName = keyof typeof icons;
