
import { AppNode, AppEdge } from '../models/types';

/**
 * Utility to generate a structured Markdown manual from the process map
 */
export const manualGenerator = {
  generateMarkdown(projectName: string, nodes: AppNode[], edges: AppEdge[]): string {
    let md = `# Process Manual: ${projectName}\n\n`;
    md += `*Generated on ${new Date().toLocaleDateString()}*\n\n`;
    
    md += `## Overview\n`;
    md += `This document provides a step-by-step guide for the **${projectName}** process map. It contains ${nodes.length} steps and ${edges.length} transitions.\n\n`;
    
    // Find start nodes (nodes with no incoming edges)
    const targetIds = new Set(edges.map(e => e.target));
    const startNodes = nodes.filter(n => !targetIds.has(n.id) && n.type !== 'groupNode');
    
    if (startNodes.length > 0) {
      md += `### Entry Points\n`;
      startNodes.forEach(n => {
        md += `- **${n.data.title}**: ${n.data.description || 'No description provided.'}\n`;
      });
      md += `\n`;
    }

    md += `## Step-by-Step Details\n\n`;
    
    // Group nodes by type for better organization
    const nodesByType: Record<string, AppNode[]> = {};
    nodes.filter(n => n.type !== 'groupNode').forEach(n => {
      const type = n.data.nodeType || 'default';
      if (!nodesByType[type]) nodesByType[type] = [];
      nodesByType[type].push(n);
    });

    // Sort nodes to try and follow logical flow (simplified)
    const sortedNodes = [...nodes].filter(n => n.type !== 'groupNode').sort((a, b) => {
      // Very basic heuristic: sort by X then Y position
      if (Math.abs(a.position.y - b.position.y) < 100) {
        return a.position.x - b.position.x;
      }
      return a.position.y - b.position.y;
    });

    sortedNodes.forEach((node, index) => {
      md += `### ${index + 1}. ${node.data.title}\n`;
      md += `**Type:** ${this.capitalize(node.data.nodeType || 'Step')}\n\n`;
      
      if (node.data.description) {
        md += `${node.data.description}\n\n`;
      } else {
        md += `*No detailed description provided for this step.*\n\n`;
      }

      // Find outgoing transitions
      const outgoing = edges.filter(e => e.source === node.id);
      if (outgoing.length > 0) {
        md += `**Next Steps:**\n`;
        outgoing.forEach(edge => {
          const target = nodes.find(n => n.id === edge.target);
          if (target) {
            const label = edge.label ? ` (via *${edge.label}*)` : '';
            md += `- Proceed to **${target.data.title}**${label}\n`;
          }
        });
        md += `\n`;
      } else {
        md += `*This is a terminal step in the process.*\n\n`;
      }
      
      md += `---\n\n`;
    });

    md += `\n*Manual generated by Process Atlas AI*`;
    
    return md;
  },

  capitalize(s: string): string {
    return s.charAt(0).toUpperCase() + s.slice(1);
  }
};
